name: c4cds
channels:
- birdhouse
- conda-forge
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# regridder
- nco
- pynco
- cdo
- python-cdo
- numpy
- netcdf4
# search
- climaf # python 2.7 only
# tests
- pytest
