name: c4cds
channels:
- conda-forge
dependencies:
- pip
- python=3.7
# pywps
- pywps=4.2
- jinja2
- click
- psutil
# regridder
- nco
- pynco
- cdo
- python-cdo
- xarray
- numpy
- netcdf4
# plot
- cartopy
- matplotlib
# tests
- pytest
- flake8
#- pip:
#  - -e git+https://github.com/geopython/pywps@master#egg=pywps
