name: c4cds
channels:
- birdhouse
- conda-forge
dependencies:
- six
# pywps
- pywps=4.1
- jinja2
- click
- psutil
# regridder
- nco
- pynco
- cdo=1.9.4
- python-cdo
- xarray
- numpy
- netcdf4=1.4.1
# plot
- cartopy
- matplotlib
# tests
- pytest
- flake8
